# Generated by Django 5.2.15 on 2026-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('accountant', 'Accountant'), ('commercial', 'Commercial')], default='admin', max_length=24),
        ),
    ]
