# Generated by Django 4.2.30 on 2026-07-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('accountant', 'Accountant'), ('commercial', 'Commercial'), ('driver', 'Driver')], default='admin', max_length=24),
        ),
    ]
