# Generated by Django 4.2.30 on 2026-07-27 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Corporate Admin'), ('travel_desk', 'Travel Desk Executive'), ('requester', 'Requester'), ('approver', 'Approver'), ('finance', 'Finance Viewer'), ('support', 'Sales/Support'), ('read_only', 'Read-Only')], default='read_only', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rentals.corporatecustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
