# Generated by Django 4.2.30 on 2026-07-27 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        ('accounts', '0004_corporatemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Corporate Admin'), ('travel_desk', 'Travel Desk Executive'), ('requester', 'Requester'), ('approver', 'Approver'), ('finance', 'Finance Viewer'), ('support', 'Sales/Support'), ('read_only', 'Read-Only')], default='read_only', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rentals.corporatecustomer')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
