# Generated by Django 4.2.30 on 2026-07-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoicedocument_invoicedeliveryattempt_and_more'),
        ('accounts', '0005_corporateinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_legal_entities',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='billing.legalentity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('accountant', 'Accountant'), ('commercial', 'Commercial'), ('driver', 'Driver'), ('operations_approver', 'Operations Approver'), ('finance_approver', 'Finance Approver'), ('auditor', 'Auditor')], default='admin', max_length=24),
        ),
    ]
