# Generated by Django 5.2.15 on 2026-07-23 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('fleet', '0005_trip_booking_type_trip_contract_trip_contract_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCloseout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('SUBMITTED', 'Submitted for Review'), ('EXCEPTION_REVIEW', 'Exception Review'), ('APPROVED', 'Approved'), ('BILLING_READY', 'Billing Ready'), ('REOPENED', 'Reopened')], default='INCOMPLETE', max_length=30)),
                ('actual_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('actual_drop_at', models.DateTimeField(blank=True, null=True)),
                ('start_odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('end_odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waiting_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('completion_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('billing_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closeout', to='fleet.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TOLL', 'Toll Charges'), ('PARKING', 'Parking Fee'), ('STATE_PERMIT_TAX', 'State / Permit Tax'), ('WAITING_CHARGE', 'Waiting Charges'), ('NIGHT_ALLOWANCE', 'Night Halt Allowance'), ('DRIVER_ALLOWANCE', 'Driver Allowance'), ('DISCOUNT', 'Discount'), ('OTHER_EXTRA', 'Other Extra Charge')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('receipt_attachment_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='billing.tripcloseout')),
            ],
        ),
    ]
