# Generated by Django 5.2.15 on 2026-07-23 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentreceipt_paymentallocation'),
        ('fleet', '0005_trip_booking_type_trip_contract_trip_contract_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Charges'), ('TOLL', 'Toll & Fastag'), ('PARKING', 'Parking Fee'), ('STATE_TAX', 'State / Entry Permit Tax'), ('MAINTENANCE', 'Vehicle Maintenance'), ('DRIVER_ALLOWANCE', 'Driver Allowance'), ('VENDOR_CHARGE', 'Outsourced Vendor Charge'), ('MISC', 'Miscellaneous Expense')], default='FUEL', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled')], default='SUBMITTED', max_length=24)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='billing.supplierprofile')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fleet.trip')),
            ],
        ),
    ]
