# Generated by Django 5.2.15 on 2026-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_supplierprofile_tripexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_state_code_snapshot',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_state_code_snapshot',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_regime',
            field=models.CharField(choices=[('INTRA_STATE', 'Intra-state CGST/SGST'), ('INTER_STATE', 'Inter-state IGST'), ('ZERO_RATED', 'Zero rated / exempt')], default='INTRA_STATE', max_length=24),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_regime',
            field=models.CharField(choices=[('INTRA_STATE', 'Intra-state CGST/SGST'), ('INTER_STATE', 'Inter-state IGST'), ('ZERO_RATED', 'Zero rated / exempt')], default='INTRA_STATE', max_length=24),
        ),
    ]
