# Generated by Django 5.2.15 on 2026-07-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_tax_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='calculation_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='source_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
