# Generated by Django 5.2.15 on 2026-07-28 09:12

from django.db import migrations, models


def backfill_invoice_bill_to(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    InvoiceTrip = apps.get_model("billing", "InvoiceTrip")
    for invoice in Invoice.objects.iterator():
        link = (
            InvoiceTrip.objects.filter(invoice_id=invoice.id)
            .select_related("trip")
            .first()
        )
        if not link:
            continue
        trip = link.trip
        Invoice.objects.filter(pk=invoice.pk).update(
            bill_to_type=trip.bill_to_type,
            bill_to_key=trip.bill_to_key,
            booking_channel=trip.booking_type,
            billing_cycle=(trip.pricing_snapshot or {}).get(
                "billing_cycle", "ON_DEMAND"
            ),
            billing_email_snapshot=trip.bill_to_email_snapshot,
            billing_phone_snapshot=trip.bill_to_phone_snapshot,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoiceline_calculation_version_and_more'),
        ('fleet', '0013_trip_bill_to_address_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to_key',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_cycle',
            field=models.CharField(default='PER_TRIP', max_length=24),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_phone_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking_channel',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.RunPython(backfill_invoice_bill_to, migrations.RunPython.noop),
    ]
