# Generated by Django 5.2.15 on 2026-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_bill_to_key_invoice_bill_to_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcloseout',
            name='blockers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tripcloseout',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tripcloseout',
            name='source_event_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tripcloseout',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
