# Generated by Django 5.2.15 on 2026-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_tripcloseout_blockers_tripcloseout_evidence_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcloseout',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tripcloseout',
            name='metering_policy',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tripcloseout',
            name='milestone_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tripcloseout',
            name='quantity_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
