# Generated by Django 5.2.15 on 2026-07-28 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_invoice_approved_at_invoice_approved_by_and_more'),
        ('media_store', '0002_uploadedasset_checksum_sha256_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('generation_version', models.CharField(default='invoice-pdf-v1', max_length=40)),
                ('status_snapshot', models.CharField(max_length=30)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('is_frozen', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_document', to='media_store.uploadedasset')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='billing.invoice')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(default=list)),
                ('channel', models.CharField(default='EMAIL', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('failure_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='billing.invoicedocument')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoicedocument',
            constraint=models.UniqueConstraint(fields=('invoice', 'version'), name='unique_invoice_document_version'),
        ),
    ]
