# Generated by Django 4.2.30 on 2026-07-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0015_invoicedocument_invoicedeliveryattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('response_status_code', models.IntegerField()),
                ('response_body', models.TextField()),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=60)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=60)),
                ('before_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('after_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('request_idempotency_key', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='WEB_CONSOLE', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
