# Generated by Django 5.2.16 on 2026-07-30 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_idempotencyregistry_financialauditevent'),
        ('fleet', '0017_fueltransaction_latitude_fueltransaction_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTACounterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('provider_type', models.CharField(default='OTA', max_length=60)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('payout_beneficiary_name', models.CharField(blank=True, max_length=150)),
                ('payout_beneficiary_account', models.CharField(blank=True, max_length=80)),
                ('payout_beneficiary_ifsc', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OTAAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=60)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('request_idempotency_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ota_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTABookingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_booking_id', models.CharField(max_length=120)),
                ('partner_reference_number', models.CharField(blank=True, max_length=120)),
                ('provider_trip_id', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('gross_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fare_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_basis', models.CharField(default='GROSS_FARE', max_length=40)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withholding_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('withholding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cancellation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('SETTLED', 'Settled'), ('EXCEPTION', 'Exception'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='PENDING', max_length=24)),
                ('monetary_sources', models.JSONField(blank=True, default=dict)),
                ('source_system', models.CharField(default='MANUAL', max_length=60)),
                ('source_payload_hash', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ota_booking_snapshots', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_ota_booking_snapshots', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ota_booking_snapshot', to='fleet.trip')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_snapshots', to='billing.otacounterparty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTASettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(max_length=120)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payout_beneficiary_name', models.CharField(blank=True, max_length=150)),
                ('payout_beneficiary_account', models.CharField(blank=True, max_length=80)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withholding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_expected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('SETTLED', 'Settled'), ('EXCEPTION', 'Exception'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='PENDING', max_length=24)),
                ('monetary_sources', models.JSONField(blank=True, default=dict)),
                ('source_system', models.CharField(default='MANUAL', max_length=60)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ota_settlement_batches', to=settings.AUTH_USER_MODEL)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='billing.otacounterparty')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_ota_settlement_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTASettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('SETTLED', 'Settled'), ('EXCEPTION', 'Exception'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='PENDING', max_length=24)),
                ('monetary_sources', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.otasettlementbatch')),
                ('booking_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='billing.otabookingsnapshot')),
            ],
            options={
                'ordering': ['batch_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='otabookingsnapshot',
            constraint=models.UniqueConstraint(fields=('counterparty', 'provider_booking_id'), name='unique_ota_provider_booking'),
        ),
        migrations.AddConstraint(
            model_name='otabookingsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('partner_reference_number', ''), _negated=True), fields=('counterparty', 'partner_reference_number'), name='unique_ota_partner_reference'),
        ),
        migrations.AddConstraint(
            model_name='otasettlementbatch',
            constraint=models.UniqueConstraint(fields=('counterparty', 'batch_reference'), name='unique_ota_settlement_batch_reference'),
        ),
        migrations.AddConstraint(
            model_name='otasettlementline',
            constraint=models.UniqueConstraint(fields=('batch', 'booking_snapshot'), name='unique_ota_settlement_line_booking'),
        ),
    ]
