# Generated by Django 5.2.16 on 2026-07-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_otacounterparty_otaauditevent_otabookingsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otacounterparty',
            name='billing_arrangement',
            field=models.CharField(choices=[('OTA_INVOICE', 'Tax invoice to OTA'), ('RIDER_INVOICE', 'Tax invoice to rider'), ('SELF_BILLED', 'Self-billed by OTA'), ('EXCEPTION_REVIEW', 'Exception review')], default='OTA_INVOICE', max_length=32),
        ),
        migrations.AddField(
            model_name='otacounterparty',
            name='commission_tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
