# Generated by Django 5.2.16 on 2026-07-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_otacounterparty_billing_arrangement_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otasettlementline',
            name='unique_ota_settlement_line_booking',
        ),
        migrations.AddField(
            model_name='otasettlementline',
            name='classification',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXACT', 'Exact'), ('SHORT', 'Short'), ('EXCESS', 'Excess'), ('MISSING', 'Missing'), ('DUPLICATE', 'Duplicate'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=24),
        ),
        migrations.AddField(
            model_name='otasettlementline',
            name='provider_booking_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='otasettlementline',
            name='booking_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='billing.otabookingsnapshot'),
        ),
        migrations.AddConstraint(
            model_name='otasettlementline',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_snapshot__isnull', False)), fields=('batch', 'booking_snapshot'), name='unique_ota_settlement_line_booking'),
        ),
    ]
