# Generated by Django 5.2.16 on 2026-07-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_remove_otasettlementline_unique_ota_settlement_line_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='linkage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='journalline',
            name='linkage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
