# Generated by Codex on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_store", "0002_uploadedasset_checksum_sha256_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedasset",
            name="file_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
