# Generated by Django 4.2.30 on 2026-07-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_trip_drop_latitude_alter_trip_drop_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='aadhar_doc_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='driver',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='driver',
            name='dl_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_doc_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='driver',
            name='pcc_doc_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='driver',
            name='police_clearance_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='authorization_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_receipt_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
