# Generated by Django 5.2.15 on 2026-07-23 14:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_trip_drop_latitude_alter_trip_drop_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('legal_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=24)),
                ('booking_contact_name', models.CharField(blank=True, max_length=120)),
                ('booking_contact_email', models.EmailField(blank=True, max_length=254)),
                ('booking_contact_phone', models.CharField(blank=True, max_length=24)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('po_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['code'], name='fleet_corpo_code_f1651b_idx'), models.Index(fields=['status'], name='fleet_corpo_status_a9a49b_idx'), models.Index(fields=['is_active'], name='fleet_corpo_is_acti_9eb1a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorporateContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('version_name', models.CharField(default='v1.0', max_length=40)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=24)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('cancellation_terms', models.TextField(blank=True)),
                ('metering_policy', models.CharField(choices=[('GARAGE_TO_GARAGE', 'Garage to Garage'), ('PICKUP_TO_DROP', 'Pickup to Drop'), ('FIXED_PACKAGE', 'Fixed Package'), ('OUTSTATION_DAILY_MINIMUM', 'Outstation Daily Minimum'), ('AIRPORT_TRANSFER', 'Airport Transfer')], default='GARAGE_TO_GARAGE', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='fleet.corporatecustomer')),
            ],
            options={
                'ordering': ['-effective_start'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('BILLING', 'Billing'), ('DISPATCH', 'Dispatch'), ('COMMERCIAL', 'Commercial'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='PRIMARY', max_length=24)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='fleet.corporatecustomer')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('vehicle_category', models.CharField(max_length=80)),
                ('duty_type', models.CharField(choices=[('LOCAL_8HR_80KM', 'Local (8h / 80km)'), ('LOCAL_12HR_120KM', 'Local (12h / 120km)'), ('OUTSTATION', 'Outstation'), ('AIRPORT_TRANSFER', 'Airport Transfer'), ('ONE_WAY', 'One-Way'), ('FULL_DAY', 'Full Day'), ('CUSTOM', 'Custom Package')], max_length=40)),
                ('included_hours', models.PositiveIntegerField(default=0)),
                ('included_km', models.PositiveIntegerField(default=0)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_km_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('switch_threshold_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('switch_threshold_km', models.PositiveIntegerField(blank=True, null=True)),
                ('outstation_daily_min_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='fleet.corporatecontract')),
            ],
            options={
                'ordering': ['city', 'vehicle_category', 'duty_type'],
                'indexes': [models.Index(fields=['contract', 'city', 'vehicle_category', 'duty_type'], name='fleet_contr_contrac_310d39_idx')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'city', 'vehicle_category', 'duty_type'), name='unique_contract_rate_key')],
            },
        ),
        migrations.CreateModel(
            name='ContractAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('OVERTIME_PER_HOUR', 'Overtime per hour'), ('OUTSTATION_PER_DAY', 'Outstation per day'), ('OVERNIGHT_DRIVER_ALLOWANCE', 'Overnight driver allowance'), ('SUNDAY_ALLOWANCE', 'Sunday allowance'), ('EARLY_START_ALLOWANCE', 'Early start allowance'), ('NIGHT_ALLOWANCE', 'Night allowance'), ('EXTRA_DUTY_ALLOWANCE', 'Extra duty allowance')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='fleet.corporatecontract')),
            ],
            options={
                'ordering': ['allowance_type'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'allowance_type'), name='unique_contract_allowance_key')],
            },
        ),
        migrations.AddIndex(
            model_name='corporatecontract',
            index=models.Index(fields=['customer', 'status', 'effective_start', 'effective_end'], name='fleet_corpo_custome_e6faff_idx'),
        ),
    ]
