# Generated by Django 5.2.15 on 2026-07-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_corporatecustomer_corporatecontract_customercontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='booking_type',
            field=models.CharField(choices=[('CORPORATE', 'Corporate'), ('ADHOC', 'Ad-hoc / Direct'), ('OTA', 'OTA / Aggregator')], default='ADHOC', max_length=24),
        ),
        migrations.AddField(
            model_name='trip',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.corporatecontract'),
        ),
        migrations.AddField(
            model_name='trip',
            name='contract_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.contractrate'),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.corporatecustomer'),
        ),
        migrations.AddField(
            model_name='trip',
            name='customer_display_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='duty_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='trip',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_category_requested',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='trip',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
