# Generated by Django 4.2.30 on 2026-07-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_driver_aadhar_doc_url_driver_aadhar_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='aadhar_doc_url',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='dl_expires_on',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_doc_url',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pcc_doc_url',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='police_clearance_expires_on',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='authorization_expires_on',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='puc_expires_on',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rc_expires_on',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tax_receipt_expires_on',
        ),
    ]
