# Generated by Django 4.2.30 on 2026-07-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_store', '__first__'),
        ('fleet', '0005_remove_driver_aadhar_doc_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='aadhaar_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_aadhaar_cards', to='media_store.uploadedasset'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_driving_licenses', to='media_store.uploadedasset'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='police_clearance_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_pccs', to='media_store.uploadedasset'),
        ),
    ]
