# Generated by Django 5.2.15 on 2026-07-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_trip_booking_type_trip_contract_trip_contract_rate_and_more'),
        ('fleet', '0006_driver_aadhaar_card_driver_driving_license_and_more'),
    ]

    operations = [
    ]
