# Generated by Django 4.2.30 on 2026-07-24 09:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_supplierprofile_tripexpense'),
        ('media_store', '0001_initial'),
        ('fleet', '0007_merge_20260723_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='baseline_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='expected_mileage_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='expected_mileage_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], default='petrol', max_length=24),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_unit',
            field=models.CharField(choices=[('litres', 'Litres'), ('kg', 'Kg'), ('kwh', 'kWh')], default='litres', max_length=24),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tank_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('transaction_datetime', models.DateTimeField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_full_fill', models.BooleanField(default=True)),
                ('source', models.CharField(default='console', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed'), ('corrected', 'Corrected')], default='submitted', max_length=24)),
                ('is_correction', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('has_anomaly', models.BooleanField(default=False)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('anomaly_review_notes', models.TextField(blank=True)),
                ('anomaly_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anomaly_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fuel_anomalies', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fuel_transactions', to=settings.AUTH_USER_MODEL)),
                ('corrected_by_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_transactions', to='fleet.fueltransaction')),
                ('corrected_from_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_history', to='fleet.fueltransaction')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to='fleet.driver')),
                ('expense_posted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transaction', to='billing.tripexpense')),
                ('odometer_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_odometers', to='media_store.uploadedasset')),
                ('receipt_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_receipts', to='media_store.uploadedasset')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-transaction_datetime'],
                'indexes': [models.Index(fields=['vehicle', 'transaction_datetime'], name='fleet_fuelt_vehicle_63eeb2_idx'), models.Index(fields=['status'], name='fleet_fuelt_status_435d10_idx'), models.Index(fields=['invoice_number', 'vendor'], name='fleet_fuelt_invoice_f371cc_idx')],
            },
        ),
    ]
