# Generated by Django 5.2.16 on 2026-07-24 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_driver_user'),
        ('media_store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_trip_otps', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_session', to='fleet.trip')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_trip_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_odometer_km', models.PositiveIntegerField()),
                ('end_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('cleanliness_ok', models.BooleanField(default=True)),
                ('fuel_level_percent', models.PositiveIntegerField(default=100)),
                ('tire_pressure_ok', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('start_idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('complete_idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_trip_checklists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trip_checklists', to=settings.AUTH_USER_MODEL)),
                ('end_odometer_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_end_odometers', to='media_store.uploadedasset')),
                ('start_odometer_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_start_odometers', to='media_store.uploadedasset')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='fleet.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip'], name='fleet_tripc_trip_id_f9c541_idx'), models.Index(fields=['start_idempotency_key'], name='fleet_tripc_start_i_68521f_idx'), models.Index(fields=['complete_idempotency_key'], name='fleet_tripc_complet_66555a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed_kmh', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_location_logs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='fleet.trip')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trip', '-timestamp'], name='fleet_tripl_trip_id_07debc_idx'), models.Index(fields=['idempotency_key'], name='fleet_tripl_idempot_8d0864_idx')],
            },
        ),
    ]
