# Generated by Django 5.2.16 on 2026-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_tripotp_tripchecklist_triplocationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='trip',
            name='drop_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('en_route_pickup', 'En route to pickup'), ('arrived_at_pickup', 'Arrived at pickup'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=24),
        ),
    ]
