# Generated by Django 5.2.15 on 2026-07-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_trip_customer_phone_trip_drop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='final_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='final_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pricing_amount_status',
            field=models.CharField(choices=[('LEGACY_UNCLASSIFIED', 'Legacy / tax treatment unknown'), ('QUOTED', 'Server-priced quote'), ('FINALIZED', 'Approved final charge')], default='LEGACY_UNCLASSIFIED', max_length=32),
        ),
        migrations.AddField(
            model_name='trip',
            name='quoted_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='quoted_taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='quoted_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
