# Generated by Django 5.2.15 on 2026-07-28 09:12

import fleet.models
from django.db import migrations, models


def backfill_trip_bill_to(apps, schema_editor):
    Trip = apps.get_model("fleet", "Trip")
    for trip in Trip.objects.select_related("customer").iterator():
        if trip.customer_id:
            customer = trip.customer
            values = {
                "bill_to_type": "CORPORATE",
                "bill_to_key": f"CORPORATE:{customer.id}",
                "bill_to_name_snapshot": customer.legal_name or customer.display_name,
                "bill_to_address_snapshot": customer.billing_address,
                "bill_to_gstin_snapshot": customer.gstin,
                "bill_to_email_snapshot": customer.billing_email,
                "bill_to_phone_snapshot": customer.billing_phone,
            }
        elif trip.booking_type == "OTA" and trip.ota_source:
            values = {
                "bill_to_type": "OTA",
                "bill_to_key": f"OTA:{trip.ota_source.strip().upper()}",
                "bill_to_name_snapshot": trip.ota_source.strip(),
            }
        else:
            values = {
                "bill_to_type": "DIRECT",
                "bill_to_name_snapshot": trip.customer_name,
                "bill_to_phone_snapshot": trip.customer_phone,
            }
        Trip.objects.filter(pk=trip.pk).update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_trip_pricing_amount_semantics'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bill_to_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='bill_to_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='trip',
            name='bill_to_gstin_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='bill_to_key',
            field=models.CharField(db_index=True, default=fleet.models.new_direct_bill_to_key, max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='bill_to_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='bill_to_phone_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='trip',
            name='bill_to_type',
            field=models.CharField(choices=[('CORPORATE', 'Corporate customer'), ('DIRECT', 'Direct customer'), ('OTA', 'OTA counterparty')], default='DIRECT', max_length=16),
        ),
        migrations.AddField(
            model_name='trip',
            name='po_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(backfill_trip_bill_to, migrations.RunPython.noop),
    ]
