# Generated by Django 5.2.15 on 2026-07-28 11:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_trip_bill_to_address_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('book_type', models.CharField(choices=[('PUBLIC', 'Public / ad-hoc'), ('CORPORATE', 'Corporate'), ('OTA', 'OTA / aggregator')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('ota_source', models.CharField(blank=True, max_length=80)),
                ('source_system', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rate_books', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_books', to='fleet.corporatecontract')),
            ],
            options={
                'ordering': ['-priority', '-effective_start', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('route_from', models.CharField(blank=True, max_length=120)),
                ('route_to', models.CharField(blank=True, max_length=120)),
                ('vehicle_category', models.CharField(blank=True, max_length=80)),
                ('duty_type', models.CharField(choices=[('LOCAL_8HR_80KM', 'Local (8h / 80km)'), ('LOCAL_12HR_120KM', 'Local (12h / 120km)'), ('OUTSTATION', 'Outstation'), ('AIRPORT_TRANSFER', 'Airport Transfer'), ('ONE_WAY', 'One-Way'), ('FULL_DAY', 'Full Day'), ('CUSTOM', 'Custom Package')], max_length=40)),
                ('included_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('included_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('extra_km_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('daily_minimum_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('waiting_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('night_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('driver_allowance_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('metering_policy', models.CharField(choices=[('GARAGE_TO_GARAGE', 'Garage to Garage'), ('PICKUP_TO_DROP', 'Pickup to Drop'), ('FIXED_PACKAGE', 'Fixed Package'), ('OUTSTATION_DAILY_MINIMUM', 'Outstation Daily Minimum'), ('AIRPORT_TRANSFER', 'Airport Transfer')], default='PICKUP_TO_DROP', max_length=32)),
                ('source_system', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='fleet.ratebook')),
            ],
            options={
                'ordering': ['rate_book', 'city', 'vehicle_category', 'duty_type', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='ratebook',
            index=models.Index(fields=['book_type', 'status', 'effective_start', 'effective_end'], name='fleet_rateb_book_ty_3ff805_idx'),
        ),
        migrations.AddIndex(
            model_name='ratebook',
            index=models.Index(fields=['contract', 'status'], name='fleet_rateb_contrac_5d070a_idx'),
        ),
        migrations.AddIndex(
            model_name='ratebook',
            index=models.Index(fields=['ota_source', 'status'], name='fleet_rateb_ota_sou_41fe15_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratebook',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_rate_book_version'),
        ),
        migrations.AddConstraint(
            model_name='ratebook',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('book_type', 'contract', 'ota_source'), name='unique_active_rate_book_scope'),
        ),
        migrations.AddConstraint(
            model_name='ratebook',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('source_system', 'source_id'), name='unique_rate_book_source'),
        ),
        migrations.AddIndex(
            model_name='ratepackage',
            index=models.Index(fields=['city', 'vehicle_category', 'duty_type'], name='fleet_ratep_city_cdd943_idx'),
        ),
        migrations.AddIndex(
            model_name='ratepackage',
            index=models.Index(fields=['route_from', 'route_to', 'duty_type'], name='fleet_ratep_route_f_5881ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratepackage',
            constraint=models.UniqueConstraint(fields=('rate_book', 'code'), name='unique_rate_package_code'),
        ),
        migrations.AddConstraint(
            model_name='ratepackage',
            constraint=models.UniqueConstraint(fields=('rate_book', 'city', 'zone', 'route_from', 'route_to', 'vehicle_category', 'duty_type'), name='unique_rate_package_scope'),
        ),
        migrations.AddConstraint(
            model_name='ratepackage',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('source_system', 'source_id'), name='unique_rate_package_source'),
        ),
    ]
