# Generated by Django 5.2.15 on 2026-07-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_ratebook_ratepackage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='calculation_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='trip',
            name='rate_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.ratepackage'),
        ),
        migrations.CreateModel(
            name='TripQuoteOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_snapshot', models.JSONField()),
                ('original_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delta_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_trip_quote_overrides', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_trip_quote_overrides', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_overrides', to='fleet.trip')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
