# Generated by Django 5.2.15 on 2026-07-28 12:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_trip_calculation_version_trip_rate_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratepackage',
            name='ota_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='ratepackage',
            name='ota_terms_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratepackage',
            name='ota_withholding_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='ota_external_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
