# Generated by Django 4.2.30 on 2026-07-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_store', '0003_uploadedasset_file_url_length'),
        ('fleet', '0016_ratepackage_ota_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='fleet.trip'),
        ),
        migrations.CreateModel(
            name='FuelTransactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_images', to='media_store.uploadedasset')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fleet.fueltransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
