# Generated by Django 5.2.16 on 2026-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_fueltransaction_latitude_fueltransaction_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrate',
            name='duty_type',
            field=models.CharField(choices=[('LOCAL_4HR_40KM', 'Local (4h / 40km)'), ('LOCAL_8HR_80KM', 'Local (8h / 80km)'), ('LOCAL_10HR_100KM', 'Local (10h / 100km)'), ('LOCAL_12HR_120KM', 'Local (12h / 120km)'), ('OUTSTATION', 'Outstation'), ('AIRPORT_TRANSFER', 'Airport Transfer'), ('ONE_WAY', 'One-Way'), ('FULL_DAY', 'Full Day'), ('CUSTOM', 'Custom Package')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ratepackage',
            name='duty_type',
            field=models.CharField(choices=[('LOCAL_4HR_40KM', 'Local (4h / 40km)'), ('LOCAL_8HR_80KM', 'Local (8h / 80km)'), ('LOCAL_10HR_100KM', 'Local (10h / 100km)'), ('LOCAL_12HR_120KM', 'Local (12h / 120km)'), ('OUTSTATION', 'Outstation'), ('AIRPORT_TRANSFER', 'Airport Transfer'), ('ONE_WAY', 'One-Way'), ('FULL_DAY', 'Full Day'), ('CUSTOM', 'Custom Package')], max_length=40),
        ),
    ]
