# Generated by Django 4.2.30 on 2026-07-22 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0005_remove_driver_aadhar_doc_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('pan_number', models.CharField(blank=True, max_length=30)),
                ('billing_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=32, unique=True)),
                ('customer_type', models.CharField(default='individual', max_length=20)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=24)),
                ('customer_email', models.EmailField(blank=True, max_length=120)),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField(blank=True)),
                ('pickup_city', models.CharField(max_length=120)),
                ('pickup_at', models.DateTimeField()),
                ('expected_return_at', models.DateTimeField()),
                ('vehicle_category', models.CharField(default='Sedan', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('vehicle_assigned', 'Vehicle Assigned'), ('driver_assigned', 'Driver Assigned'), ('ready', 'Ready'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_travelled', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_hours_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rentals.corporatecustomer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='fleet.driver')),
            ],
            options={
                'ordering': ['-pickup_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('package_type', models.CharField(choices=[('local', 'Local Package'), ('airport', 'Airport Transfer'), ('outstation', 'Outstation')], default='local', max_length=30)),
                ('included_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('included_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('extra_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('driver_allowance_per_day', models.DecimalField(decimal_places=2, default=300.0, max_digits=8)),
                ('night_stay_charge', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_km_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='rentals.corporatecustomer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='rentals.rentalpackage')),
            ],
            options={
                'ordering': ['company', 'city', 'package'],
            },
        ),
        migrations.CreateModel(
            name='RentalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('distance_travelled', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours_used', models.DecimalField(decimal_places=2, max_digits=8)),
                ('included_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('included_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_km_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_hour_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='rentals.rentalbooking')),
            ],
        ),
        migrations.CreateModel(
            name='RentalFuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_quantity_liters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_reading', models.PositiveIntegerField()),
                ('fuel_station', models.CharField(blank=True, max_length=120)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='rentals.rentalbooking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RentalChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('start', 'Pre-Rental Start'), ('end', 'Post-Rental End')], max_length=10)),
                ('front_photo', models.TextField(blank=True)),
                ('rear_photo', models.TextField(blank=True)),
                ('left_photo', models.TextField(blank=True)),
                ('right_photo', models.TextField(blank=True)),
                ('dashboard_photo', models.TextField(blank=True)),
                ('odometer_photo', models.TextField(blank=True)),
                ('fuel_gauge_photo', models.TextField(blank=True)),
                ('odometer_reading', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='rentals.rentalbooking')),
            ],
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rentals.rentalpackage'),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='fleet.vehicle'),
        ),
    ]
