# Generated by Django 4.2.30 on 2026-07-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=32, unique=True)),
                ('passenger_name', models.CharField(max_length=120)),
                ('passenger_phone', models.CharField(max_length=24)),
                ('passenger_email', models.EmailField(blank=True, default='', max_length=254)),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField(blank=True, default='')),
                ('pickup_city', models.CharField(max_length=120)),
                ('pickup_at', models.DateTimeField()),
                ('expected_return_at', models.DateTimeField()),
                ('vehicle_category', models.CharField(default='Sedan', max_length=40)),
                ('cost_centre', models.CharField(blank=True, default='', max_length=80)),
                ('po_reference', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approval_required', 'Approval Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='submitted', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('quote_base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quote_extra_km_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('quote_extra_hour_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('quote_driver_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='rentals.corporatecustomer')),
            ],
            options={
                'ordering': ['-pickup_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=24)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profiles', to='rentals.corporatecustomer')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='CorporateApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_po', models.BooleanField(default=False)),
                ('require_cost_centre', models.BooleanField(default=False)),
                ('approval_threshold_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_policy', to='rentals.corporatecustomer')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequestAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField()),
                ('reason', models.TextField(blank=True, default='')),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='rentals.bookingrequest')),
            ],
            options={
                'ordering': ['-amended_at'],
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='rentals.guestprofile'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='rentals.rentalpackage'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
