# Generated by Django 4.2.30 on 2026-07-27 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_bookingrequest_guestprofile_corporateapprovalpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=32)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=24)),
                ('notification_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='corporateapprovalpolicy',
            name='location_precision_digits',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='RentalBookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_customer_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rentals.rentalbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalBookingLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='rentals.rentalbooking')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['booking', '-timestamp'], name='rentals_ren_booking_3df01b_idx')],
            },
        ),
    ]
