# Generated by Django 4.2.30 on 2026-07-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_portalsupportcase_portalauditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalHandoffQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='failed', max_length=20)),
                ('error_message', models.TextField()),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_queue', to='rentals.bookingrequest')),
            ],
        ),
    ]
