# Generated by Django 5.2.15 on 2026-07-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_ratepackage_ota_commission_rate_and_more'),
        ('rentals', '0005_portalhandoffqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecustomer',
            name='fleet_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_portal_customer', to='fleet.corporatecustomer'),
        ),
    ]
