# Generated by Django 5.2.16 on 2026-07-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0017_fueltransaction_latitude_fueltransaction_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMTBookingLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('partner_reference_number', models.CharField(blank=True, max_length=120)),
                ('order_reference_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='SEARCHED', max_length=40)),
                ('search_payload', models.JSONField(blank=True, default=dict)),
                ('block_payload', models.JSONField(blank=True, default=dict)),
                ('paid_payload', models.JSONField(blank=True, default=dict)),
                ('cancel_payload', models.JSONField(blank=True, default=dict)),
                ('booking_details_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_facts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_lifecycle', to='fleet.trip')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('search_id', ''), _negated=True), fields=('search_id',), name='unique_mmt_lifecycle_search_id'), models.UniqueConstraint(condition=models.Q(('partner_reference_number', ''), _negated=True), fields=('partner_reference_number',), name='unique_mmt_lifecycle_partner_reference'), models.UniqueConstraint(condition=models.Q(('order_reference_number', ''), _negated=True), fields=('order_reference_number',), name='unique_mmt_lifecycle_order_reference')],
            },
        ),
        migrations.CreateModel(
            name='MMTLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SEARCH', 'Search'), ('MARKETPLACE_SEARCH', 'Marketplace Search'), ('BLOCK', 'Block'), ('PAID', 'Paid'), ('CANCEL', 'Cancel'), ('CUSTOMER_ARRIVED', 'Customer Arrived'), ('BOOKING_DETAILS', 'Booking Details')], max_length=40)),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('search_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('partner_reference_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('order_reference_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_facts', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmt_lifecycle_events', to='fleet.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'search_id'], name='makemytrip__event_t_e75285_idx'), models.Index(fields=['event_type', 'order_reference_number'], name='makemytrip__event_t_1e5b65_idx')],
            },
        ),
    ]
